### ISSUE TITLE
where to exhaustively document available koop providers?

### ISSUE THREAD

**Issue by jgravois** [koopjs/koop-sample-provider#1]
sorry for the issue only tangentially related to this repo.

i think having some authoritative documentation (particularly on existing providers) to link to would make keeping the doc up to date a lot more realistic than having content peppered throughout individual repos.

* are things like the [wiki providers doc](https://github.com/Esri/koop/wiki/Koop-Providers-(an-ecosystem)) we created before worth preserving?
* alternatively, perhaps we should be thinking about a wiki or dedicated documentation repo within [koopjs](http://github.com/koopjs)?

**Comment by ngoldman** [comment]
@jgravois I agree, and I think this effort could be part of the doc site I'm proposing in https://github.com/Esri/koop/issues/128

I searched through all of github and starred all the koop repos I could find -- will do a dump of that somewhere soon. There are a lot in the wild, many using different versions and implementations. Would be good to bring anything we (Esri) are working on under an official banner (i.e. http://github.com/koopjs) and index third-party efforts too give them extra props and community help and make sure the providers and plugins are keeping up with changes in koop.

**Comment by chelm** [comment]
Yes! This will be great to have a centralized list of all providers, plugins, etc. I've just moved several of my repos over koopjs and I'm going to hold off on the remaining ones in my repo since they are mostly experiments and some cookbooks for deploying koop (which may actually move over too). 

https://github.com/search?q=user%3Achelm+koop

In terms of central documentation, it'll be great get a jump start on that next week and at the very least start compiling some skeleton docs on what we want doc'd and where.

**Comment by ngoldman** [comment]
Do it here! https://github.com/koopjs/koopjs.github.io/blob/master/docs/providers.md
